# .forge-lock.hcl — DO NOT EDIT MANUALLY
# Generated by forge. Changes will be overwritten on sync.

blueprint {
  registry_url = "/Users/donaldgifford/code/forge-registry"
  name         = "homelab-go"
  path         = "homelab/go"
}

created_at    = "2026-06-22T12:39:06.140185Z"
last_synced   = "2026-06-22T12:39:06.140185Z"
forge_version = "0.7.0"

variables {
  git_host               = "github.com"
  git_provider           = "github"
  go_version             = "1.26.4"
  license                = "Apache-2.0"
  project_description    = "An idiomatic golang sdk for Proxmox"
  project_name           = "proxmox-go-sdk"
  project_org            = "donaldgifford"
  renovate_config_prefix = "github"
}

default ".checkmake.ini" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:123f1dc4a0f6e608cd57546d72894791ef719ad07cc0fdd53016d57557cb9284"
}

default ".claude/settings.json" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:7fa2145b3bc9a192465144e24e2179d6062debdc730ea5012ef11a73982b2eb7"
}

default ".docz.yaml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:f3fb2387d31e3b07fa2a1efdf3e974814b13113c763a7b82d7425eb2967bbcfc"
}

default ".github/labeler.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:d249f58945cdffbb34b9cf9a50e12e82394e09413d14657771d8e3fe4408b81f"
}

default ".github/workflows/pr-labels.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:9d0bbe7ec5e56ac192a21ed557d5dc700375c60b555a874bc22c05eb57bd86d4"
}

default ".makefmt.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:c56b8f4be0b7722a0e8fda97faf4d8c29e4ff75193acf663bf5a5b0e7fbf4808"
}

default ".markdownlint.yaml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:dc9182bd0b399616bd2b6933eb4b2a756674cedb43dbea914cf61f9180e3fc92"
}

default ".prettierrc.yaml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:402823be7f1d14a6bdd7a8801c6392f7b8e74675e842aa355fccc07766b538d8"
}

default ".yamlfmt.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:d214a4f56043cad5e01bd70e3530155df3bf7372bd2571aba87bcee0c1dcca73"
}

default ".yamllint.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:3f8575b37ea4a59395110326535d36573208fc6495ac47e357512fa7b8bbf7a9"
}

default ".env.example.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:fef3a762c5fcb7fd9c5a85781bf294dd7bc2ce864d592c87c381d7afc60087cf"
}

default ".github/workflows/labels-sync.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:78328a1824c5fbbf1b5bbc0973ab5bcef8a891d5e61d36ceff5219510975c33e"
}

default ".github/workflows/lint.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:c6436894547134b34a05b957597e6955a0ec3f2080ae3d4c7923d6cc97dadde6"
}

default ".github/workflows/trufflehog.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:7aba0b644b151b40e2a8e20ae2267bb3f900ccb030d6d0f16664eeacbf317101"
}

default "catalog-info.yaml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:1d00acbeee8e87397edc558589447afff8b27fcab42638b3708bf9310f8138a5"
}

default "docs/index.md.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:575ad16813b71619f703e8e2b9ed60661e853205ea851829e8d3207eeea84e79"
}

default "labels.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:7030a2ff9efddd475aed845b1b0125dc538b420d0a899b29700462000b4cc77b"
}

default "mise.toml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:4c4c670f3601d76fde2b0e104a2241add70615b4461a6e32fceea7b1e35f5cad"
}

default "mkdocs.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:338bb4c869bc18b7495cb71fe5005525d75d43dd953ae155c4b35f24f375542b"
}

default "renovate.json5.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:8f054bc1b1ccbd32bb561ff0e7aeba9a6851531848d7c1a159cf1fd404130cc9"
}
