package main

import (
	"bytes"
	"compress/gzip"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const apidocJS = `const apiSchema = [
   { "path" : "/version", "info" : { "GET" : {} } },
   { "path" : "/nodes/{node}/qemu", "info" : { "GET" : {}, "POST" : {} } }
];`

func writeTemp(t *testing.T, name, content string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(p, []byte(content), 0o600); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
	return p
}

func TestRunUpdateThenNoDrift(t *testing.T) {
	t.Parallel()
	apidoc := writeTemp(t, "apidoc.js", apidocJS)
	baseline := filepath.Join(t.TempDir(), "baseline.json")

	// -update writes the baseline and reports no drift.
	report, drift, err := run(&options{apidoc: apidoc, baseline: baseline, update: true})
	if err != nil {
		t.Fatalf("run(update): %v", err)
	}
	if drift {
		t.Error("run(update) drift = true, want false")
	}
	if !strings.Contains(report, "baseline updated") {
		t.Errorf("update output = %q, want 'baseline updated'", report)
	}

	// Diffing the same apidoc against the fresh baseline: no drift.
	report, drift, err = run(&options{apidoc: apidoc, baseline: baseline})
	if err != nil {
		t.Fatalf("run(diff): %v", err)
	}
	if drift {
		t.Errorf("run(diff) drift = true, want false; output=%q", report)
	}
}

func TestRunDetectsDrift(t *testing.T) {
	t.Parallel()
	apidoc := writeTemp(t, "apidoc.js", apidocJS)
	// Baseline missing the qemu POST endpoint -> apidoc has drift (added).
	baseline := writeTemp(t, "baseline.json", `[
	  {"method":"GET","path":"/version"},
	  {"method":"GET","path":"/nodes/{node}/qemu"}
	]`)

	report, drift, err := run(&options{apidoc: apidoc, baseline: baseline})
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if !drift {
		t.Fatal("run drift = false, want true")
	}
	if !strings.Contains(report, "+ POST /nodes/{node}/qemu") {
		t.Errorf("drift output = %q, want the added POST endpoint", report)
	}
}

// TestRunGzippedApidoc covers the committed-artifact path: the real apidoc is
// checked in gzipped (IMPL-0003 OQ-1a) and detected by magic bytes.
func TestRunGzippedApidoc(t *testing.T) {
	t.Parallel()
	var buf bytes.Buffer
	zw := gzip.NewWriter(&buf)
	if _, err := zw.Write([]byte(apidocJS)); err != nil {
		t.Fatalf("gzip write: %v", err)
	}
	if err := zw.Close(); err != nil {
		t.Fatalf("gzip close: %v", err)
	}
	apidoc := writeTemp(t, "apidoc.js.gz", buf.String())
	baseline := filepath.Join(t.TempDir(), "baseline.json")

	report, drift, err := run(&options{apidoc: apidoc, baseline: baseline, update: true})
	if err != nil {
		t.Fatalf("run(update, gz): %v", err)
	}
	if drift {
		t.Error("run(update, gz) drift = true, want false")
	}
	if !strings.Contains(report, "baseline updated: 3 endpoint(s)") {
		t.Errorf("gz update output = %q, want 3 endpoints", report)
	}

	// A truncated gzip stream is an operational error, not silent garbage.
	broken := writeTemp(t, "broken.js.gz", buf.String()[:8])
	if _, _, err := run(&options{apidoc: broken, baseline: baseline}); err == nil {
		t.Error("run(truncated gzip) error = nil, want non-nil")
	}
}

func TestRunFileErrors(t *testing.T) {
	t.Parallel()
	if _, _, err := run(&options{apidoc: "/nonexistent/apidoc.js", baseline: "/nonexistent/baseline.json"}); err == nil {
		t.Error("run(missing apidoc) error = nil, want non-nil")
	}
}

// coverageBaseline and coverageRoutes are a fixture pair the real mock cannot
// stand in for: measuring mockpve's whole route table against a two-endpoint
// baseline would report every route as fabricated.
const coverageBaseline = `[
  {"method":"GET","path":"/version"},
  {"method":"GET","path":"/nodes/{node}/qemu"},
  {"method":"POST","path":"/nodes/{node}/qemu"}
]`

const coverageAnnotations = `baseline:
  pve_version: "9.2.4"
  source: "fixture"
  captured: "2026-01-01"
`

var coverageRoutes = []string{
	"GET /api2/json/version",
	"GET /api2/json/nodes/{node}/qemu",
}

// coverageOpts is the happy-path coverage invocation, writing into a temp dir.
func coverageOpts(t *testing.T) *options {
	t.Helper()
	return &options{
		coverage:    true,
		baseline:    writeTemp(t, "baseline.json", coverageBaseline),
		annotations: writeTemp(t, "annotations.yaml", coverageAnnotations),
		out:         filepath.Join(t.TempDir(), "COVERAGE.md"),
		routes:      coverageRoutes,
	}
}

func TestRunCoverageWritesThenVerifies(t *testing.T) {
	t.Parallel()
	opts := coverageOpts(t)

	report, fail, err := run(opts)
	if err != nil {
		t.Fatalf("run(coverage): %v", err)
	}
	if fail {
		t.Errorf("run(coverage) fail = true, want false; output=%q", report)
	}
	if !strings.Contains(report, "2 of 3 endpoint(s) covered (66.7%)") {
		t.Errorf("write output = %q, want the covered summary", report)
	}
	written, err := os.ReadFile(opts.out)
	if err != nil {
		t.Fatalf("read written report: %v", err)
	}
	if !bytes.HasPrefix(written, []byte("<!-- Generated by")) {
		t.Errorf("written report does not start with the generated marker: %.40q", written)
	}

	// -check against what was just written: current.
	opts.check = true
	report, fail, err = run(opts)
	if err != nil {
		t.Fatalf("run(coverage -check): %v", err)
	}
	if fail {
		t.Errorf("run(coverage -check) fail = true on a fresh report; output=%q", report)
	}
	if !strings.Contains(report, "is current") {
		t.Errorf("check output = %q, want 'is current'", report)
	}
}

// A hand-edited report fails the drift check — the doc is machine-owned.
func TestRunCoverageDetectsDrift(t *testing.T) {
	t.Parallel()
	opts := coverageOpts(t)
	if _, _, err := run(opts); err != nil {
		t.Fatalf("run(coverage): %v", err)
	}
	if err := os.WriteFile(opts.out, []byte("# hand-written\n"), 0o600); err != nil {
		t.Fatalf("tamper: %v", err)
	}

	opts.check = true
	report, fail, err := run(opts)
	if err != nil {
		t.Fatalf("run(coverage -check): %v", err)
	}
	if !fail {
		t.Fatal("run(coverage -check) fail = false on a tampered report, want true")
	}
	if !strings.Contains(report, "is stale") || !strings.Contains(report, "just coverage") {
		t.Errorf("drift output = %q, want the stale-report message", report)
	}
}

// The fabrication guard fails the run and, crucially, fails it BEFORE writing:
// a report naming endpoints that do not exist must never reach disk.
func TestRunCoverageGuardBlocksTheWrite(t *testing.T) {
	t.Parallel()
	opts := coverageOpts(t)
	opts.routes = append(opts.routes, "GET /api2/json/cluster/sdn/fabrics")

	report, fail, err := run(opts)
	if err != nil {
		t.Fatalf("run(coverage): %v", err)
	}
	if !fail {
		t.Fatal("run(coverage) fail = false with a fabricated route, want true")
	}
	if !strings.Contains(report, "/cluster/sdn/fabrics") {
		t.Errorf("guard output = %q, want the offending route named", report)
	}
	if _, err := os.Stat(opts.out); !os.IsNotExist(err) {
		t.Errorf("the report was written despite the guard failing (stat err = %v)", err)
	}
}

// Without -out the report goes to stdout, which is how a human eyeballs it.
func TestRunCoverageToStdout(t *testing.T) {
	t.Parallel()
	opts := coverageOpts(t)
	opts.out = ""

	report, fail, err := run(opts)
	if err != nil {
		t.Fatalf("run(coverage): %v", err)
	}
	if fail {
		t.Error("run(coverage) fail = true, want false")
	}
	if !strings.Contains(report, "## Summary") {
		t.Errorf("stdout output is not the report: %.80q", report)
	}
}

func TestRunCoverageFileErrors(t *testing.T) {
	t.Parallel()
	opts := coverageOpts(t)
	opts.annotations = "/nonexistent/annotations.yaml"
	if _, _, err := run(opts); err == nil {
		t.Error("run(coverage, missing annotations) error = nil, want non-nil")
	}

	opts = coverageOpts(t)
	opts.check = true // -check with nothing committed yet.
	if _, _, err := run(opts); err == nil {
		t.Error("run(coverage -check, missing report) error = nil, want non-nil")
	}
}

// Flag combinations that would silently check nothing are rejected, so a typo in
// a CI invocation fails loudly instead of passing.
func TestOptionsValidate(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name string
		opts options
		want string
	}{
		{"no baseline", options{apidoc: "a.js"}, "-baseline is required"},
		{"no apidoc", options{baseline: "b.json"}, "-apidoc is required"},
		{
			"coverage flags in schema-diff mode",
			options{apidoc: "a.js", baseline: "b.json", out: "c.md"},
			"apply to -coverage only",
		},
		{
			"coverage without annotations",
			options{coverage: true, baseline: "b.json"},
			"-annotations is required",
		},
		{
			"update in coverage mode",
			options{coverage: true, baseline: "b.json", annotations: "a.yaml", update: true},
			"-update applies to schema-diff mode only",
		},
		{
			"check without out",
			options{coverage: true, baseline: "b.json", annotations: "a.yaml", check: true},
			"-check needs -out",
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			err := tc.opts.validate()
			if err == nil {
				t.Fatalf("validate() = nil, want an error containing %q", tc.want)
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("validate() = %v, want an error containing %q", err, tc.want)
			}
		})
	}

	valid := []options{
		{apidoc: "a.js", baseline: "b.json"},
		{apidoc: "a.js", baseline: "b.json", update: true},
		{coverage: true, baseline: "b.json", annotations: "a.yaml"},
		{coverage: true, baseline: "b.json", annotations: "a.yaml", out: "c.md", check: true},
	}
	for i, opts := range valid {
		if err := opts.validate(); err != nil {
			t.Errorf("valid[%d].validate() = %v, want nil", i, err)
		}
	}
}
